path: data/processed/almoxarifado_dataset
train: images/train
val: images/val
test: images/test
nc: 8
names:
  0: produto_vencido
  1: sem_epi
  2: acesso_nao_autorizado
  3: produto_fora_posicao
  4: caixa_aberta
  5: temperatura_anomala
  6: empilhamento_incorreto
  7: pragas
